# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Run Automation Test

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose automation suite: RegressionSuite or SmokeSuite'
        required: true
        default: SmokeSuite
      browser:
        description: 'Choose browser'
        required: true
        default: chrome

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install ChromeDriver 130
        run: |
          wget -q https://chromedriver.storage.googleapis.com/130.0.0/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable


      - name: Verify ChromeDriver Version
        run: chromedriver --version

      - name: Run Automation Suite
        run: mvn clean install -Dci_cd=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=suites/${{ github.event.inputs.suite }} -PCustomSuite

    
